apiVersion: harness.io/v1
kind: Component
type: service
identifier: react_parson_one
name: React Parson One
owner: user:account/todd.parson@harness.io
orgIdentifier: sandbox
projectIdentifier: parson
spec:
  lifecycle: experimental
  sourceCode:
    provider: Github
    repoName: monorepo-idp-example
    connectorRef: parsonghharnessidpsandbox
    branch: main
    monoRepo: true
    monoRepoSubDirectoryPath: react-parson-one
    url: https://github.com/harness-idp-sandbox/monorepo-idp-example/tree/main/react-parson-one
metadata:
  description: Testing for POC
  annotations:
    github.com/project-slug: harness-idp-sandbox/monorepo-idp-example
    backstage.io/source-location: url:https://github.com/harness-idp-sandbox/monorepo-idp-example/tree/main/react-parson-one
  links:
  - title: Source repository
    url: https://github.com/harness-idp-sandbox/monorepo-idp-example
  - title: App folder (monorepo)
    url: https://github.com/harness-idp-sandbox/monorepo-idp-example/tree/main/react-parson-one
  tags:
  - react
  - monorepo
  - dev
