# Cookiecutter-rendered catalog definition for Harness IDP 2.0
# Docs: IDP 2.0 entity schema & fields (identifier/name/type/owner). TechDocs annotation. 
# - https://developer.harness.io/docs/internal-developer-portal/catalog/catalog-yaml/
# - https://developer.harness.io/docs/internal-developer-portal/techdocs/enable-docs/

apiVersion: harness.io/v1
kind: Component

# Machine-friendly unique key
identifier: omf_react_one
scope: ACCOUNT

# Human display name
name: omf react one

# Common types: service | library | docs | delegate
type: service

# Owner can be user or group (e.g., group:platform-team)
owner: user:account/todd.parson@harness.io

metadata:
  namespace: default
  description: Testing for POC
  annotations:
    # TechDocs looks inside the app repo for this monorepo
    backstage.io/techdocs-ref: dir:omf-react-one

    # Helpful for plugins/deeplinks
    github.com/project-slug: harness-idp-sandbox/monorepo-idp-example

    # Optional direct link to this app folder on default branch
    backstage.io/source-location: >-
      url:https://github.com/harness-idp-sandbox/monorepo-idp-example/tree/main/omf-react-one

  links:
    - title: Source repository
      url: https://github.com/harness-idp-sandbox/monorepo-idp-example
    - title: App folder (monorepo)
      url: https://github.com/harness-idp-sandbox/monorepo-idp-example/tree/main/omf-react-one

  tags:
    - react
    - monorepo
    - dev
    
spec:
  lifecycle: experimental
#  sourceCode:
#    provider: Github
#    repoName: monorepo-idp-example
#    connectorRef: account.IDP_GitHub_Sandbox_for_Testing
#    branch: main
#    monoRepo: true
#    monoRepoSubDirectoryPath: omf-react-one
  # Add relationships later if/when they exist:
  # dependsOn:
  #   - component:default/some-backend
  # providesApis:
  #   - api:default/omf-react-one-api
