name: oidc-smoke
on:
  workflow_dispatch: {}
permissions: { id-token: write, contents: read }
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GHA_ROLE_ARN }}
          aws-region: us-east-1
      - name: Who am I?
        run: aws sts get-caller-identity
